const employeesData = [
  {
    id: 1,
    firstName: "John",
    lastName: "Doe",
    jobTitle: "Software Engineer",
    department: "Engineering",
    salary: 75000,
    hireDate: "2022-03-15",
  },
  {
    id: 2,
    firstName: "Jane",
    lastName: "Smith",
    jobTitle: "Marketing Specialist",
    department: "Marketing",
    salary: 60000,
    hireDate: "2021-08-20",
  },
  {
    id: 3,
    firstName: "Michael",
    lastName: "Johnson",
    jobTitle: "Sales Representative",
    department: "Sales",
    salary: 55000,
    hireDate: "2022-01-10",
  },
  {
    id: 4,
    firstName: "Emily",
    lastName: "Brown",
    jobTitle: "HR Manager",
    department: "Human Resources",
    salary: 70000,
    hireDate: "2020-12-05",
  },
  {
    id: 5,
    firstName: "David",
    lastName: "Wilson",
    jobTitle: "Data Analyst",
    department: "Data Analytics",
    salary: 65000,
    hireDate: "2021-11-28",
  },
  {
    id: 6,
    firstName: "Sarah",
    lastName: "Lee",
    jobTitle: "Graphic Designer",
    department: "Creative",
    salary: 58000,
    hireDate: "2022-05-10",
  },
  {
    id: 7,
    firstName: "Robert",
    lastName: "Taylor",
    jobTitle: "Customer Support Specialist",
    department: "Customer Service",
    salary: 52000,
    hireDate: "2022-07-15",
  },
  {
    id: 8,
    firstName: "Karen",
    lastName: "Miller",
    jobTitle: "Financial Analyst",
    department: "Finance",
    salary: 70000,
    hireDate: "2021-03-19",
  },
  {
    id: 9,
    firstName: "Daniel",
    lastName: "Moore",
    jobTitle: "Product Manager",
    department: "Product Management",
    salary: 80000,
    hireDate: "2020-09-08",
  },
  {
    id: 10,
    firstName: "Laura",
    lastName: "Anderson",
    jobTitle: "Operations Manager",
    department: "Operations",
    salary: 75000,
    hireDate: "2021-01-25",
  },
  {
    id: 11,
    firstName: "Christopher",
    lastName: "Davis",
    jobTitle: "Quality Assurance Tester",
    department: "Quality Assurance",
    salary: 60000,
    hireDate: "2022-04-14",
  },
  {
    id: 12,
    firstName: "Jennifer",
    lastName: "Harris",
    jobTitle: "UX/UI Designer",
    department: "Design",
    salary: 62000,
    hireDate: "2021-09-30",
  },
  {
    id: 13,
    firstName: "James",
    lastName: "Martin",
    jobTitle: "Network Administrator",
    department: "IT",
    salary: 67000,
    hireDate: "2020-12-15",
  },
  {
    id: 14,
    firstName: "Amanda",
    lastName: "Clark",
    jobTitle: "Accountant",
    department: "Finance",
    salary: 72000,
    hireDate: "2021-02-08",
  },
  {
    id: 15,
    firstName: "Matthew",
    lastName: "White",
    jobTitle: "Project Manager",
    department: "Project Management",
    salary: 80000,
    hireDate: "2020-11-05",
  },
  {
    id: 16,
    firstName: "Linda",
    lastName: "Thompson",
    jobTitle: "Legal Counsel",
    department: "Legal",
    salary: 85000,
    hireDate: "2021-06-20",
  },
  {
    id: 17,
    firstName: "William",
    lastName: "Walker",
    jobTitle: "Business Analyst",
    department: "Business Analysis",
    salary: 68000,
    hireDate: "2022-02-17",
  },
  {
    id: 18,
    firstName: "Mary",
    lastName: "Lewis",
    jobTitle: "Customer Relations Manager",
    department: "Customer Service",
    salary: 70000,
    hireDate: "2021-05-12",
  },
  {
    id: 19,
    firstName: "Joseph",
    lastName: "Hill",
    jobTitle: "Software Developer",
    department: "Engineering",
    salary: 75000,
    hireDate: "2021-03-08",
  },
  {
    id: 20,
    firstName: "Patricia",
    lastName: "Baker",
    jobTitle: "Human Resources Specialist",
    department: "Human Resources",
    salary: 60000,
    hireDate: "2022-08-22",
  },
];

export default employeesData;
